### ISSUE TITLE
column-reverse and row-reverse

### ISSUE THREAD

**Issue by daniel-bergmann** [Basilcss/core#16]
### flex direction

flex column-reverse and row-reverse missing

**Comment by bymunajat** [comment]
@daniel-bergmann may i help you?

**Comment by daniel-bergmann** [comment]
Hi there @bymunajat, be my guest! Remember to add the rule for big screens as well. :)

**Comment by daniel-bergmann** [comment]
@bymunajat is there an update on this issue?

**Comment by Akash1965** [comment]
Hi @daniel-bergmann if this issue is still not resolved then may I help you with this issue??

**Comment by daniel-bergmann** [comment]
@Akash1965 be my guest!

**Comment by Akash1965** [comment]
Hi @daniel-bergmann I have made the PR. Hope you'll like it. In case of any modifications do let me know. I will fix it.

**Comment by daniel-bergmann** [comment]
Great work, it will appear in the framework on next update! 👯‍♀️
