### ISSUE TITLE
make all <a> tags visible with an extinct color, basil's color is green for example

### ISSUE THREAD

**Issue by daniel-bergmann** [Basilcss/core#2]
add underline on non hover and color on hover

**Comment by SrNightmare09** [comment]
hey! i thibk i might be able to help on this

**Comment by adk7712** [comment]
hey ! i think i might be able to help on this one!

**Comment by daniel-bergmann** [comment]
@SrNightmare09, great, go ahead!

**Comment by adk7712** [comment]
@daniel-bergmann can you be more specific with what you wish to achieve? And it would also be helpful if you could provide with the exact colors you wish to see.

**Comment by daniel-bergmann** [comment]
@SrNightmare09 simply have all <a> tags visible as the green --accent variable in the css file.

**Comment by adk7712** [comment]
@daniel-bergmann so you want to have a distinct color when the link has been clicked once?

**Comment by daniel-bergmann** [comment]
@SrNightmare09 the original <a> color is blue but we want it to be green to match the design

**Comment by adk7712** [comment]
@daniel-bergmann when i import the framework on a simple react app, the link is green only. i can send a screenshot as well as the code if u wish to see it

**Comment by adk7712** [comment]
> @daniel-bergmann when i import the framework on a simple react app, the link is green only. i can send a screenshot as well as the code if u wish to see it

even when i use the framework on online react compilers such as replit, i can clearly see the accent green on hovering upon a link. The link when there is no hover is black in itself tho.

**Comment by daniel-bergmann** [comment]
@SrNightmare09 great, can you make it green without the hover?

**Comment by adk7712** [comment]
@daniel-bergmann sure!
