### ISSUE TITLE
docs: minor styling issues in documentation

### ISSUE THREAD

**Issue by adk7712** [Basilcss/core#20]
Going through the documentation and I spotted this. I don't believe this was intentional and I hope you can fix it. I was also wondering if there is any way to contribute to the documentation of the project. Thanks!

![image](https://github.com/Basilcss/core/assets/73314216/7ae12064-9287-4076-9b5b-b4439c21749a)

**Comment by daniel-bergmann** [comment]
good spot! you are welcome to go ahead and try it out by forking the repo and make a pull request

**Comment by adk7712** [comment]
@daniel-bergmann can you guide me as to where I can contribute to the official documentation.

Edit: I found it. Sorry for the bother.

**Comment by daniel-bergmann** [comment]
Sorry for the late reply, the docs is a simple nuxt app with one global stylesheet and the contents of the docs can be found in a .md file. 

## text content
https://github.com/Basilcss/docs/blob/main/content/index.md

## global styles
https://github.com/Basilcss/docs/blob/main/assets/styles/global.scss

Let me know if there is anything :)
