### ISSUE TITLE
Detecting flex properties

### ISSUE THREAD

**Issue by Patrikur** [Basilcss/core#23]
Howdy,

As I was reading through the class names, it was at some point hard to detect whether a flex boxes justify-content or align-items was centered etc.
Suggestion: add a justify and align to the class names. E. g.: `flex-justifyCenter-alignCenter` makes it more readable than `flex-center-center`. It would also eliminate the issue, if you are using just the align or just the justify property.

**Comment by daniel-bergmann** [comment]
Very good idea! Would you like to implement it and make a pull request? @Patrikur

**Comment by Patrikur** [comment]
Sure, will do!
