### ISSUE TITLE
Design a better logo for the framework

### ISSUE THREAD

**Issue by daniel-bergmann** [Basilcss/core#4]
just something high res and minimal like a single green leaf of some sort

**Comment by adk7712** [comment]
Hey! I wanted to contribute to this project. I think this is a good place to start. I can share some ideas and you can pick out the logo you like. I would also like to get a brief on how I can contribute to this project!

**Comment by daniel-bergmann** [comment]
@SrNightmare09 

Hi there!

I'll go ahead and make the contribution file, I'll let you know when it's ready this evening. :)

**Comment by daniel-bergmann** [comment]
here you go @SrNightmare09 ,

https://github.com/Basilcss/core/blob/main/CONTRIBUTING.md

when it comes to adding a new logo to the framework, simply add it here in a comment. We will then review and accept if it suits well.

**Comment by adk7712** [comment]
Great! I would like to get started by kindly asking you to list out whatever you would like to see in your logo. You have already mentioned about it being minimalist and high res. Anything else? Do you want it to be similar to your current logo?

**Comment by daniel-bergmann** [comment]
Good question @SrNightmare09,

I think having it a simple green leaf of some sort would work great. If you have any great ideas just go ahead and design as you want. We're open for all ideas.

**Comment by adk7712** [comment]
Alright, on it!

**Comment by adk7712** [comment]
Thanks for the assignment! And a bigger thank you for adding me to your organization!!

**Comment by adk7712** [comment]
Hello Daniel, 

here is a little something I have been working on, let me know your opinions about it!

![basil](https://github.com/Basilcss/core/assets/73314216/cf83e491-bb30-40c6-956e-38080a32bc70)

**Comment by daniel-bergmann** [comment]
@SrNightmare09 It looks good, could you make it a bit more minimal and green?

**Comment by adk7712** [comment]
> @SrNightmare09 It looks good, could you make it a bit more minimal and green?

Can you guide me through as to in what ways I can make the logo more minimal?

As for making it green, I will make it green once we finalize the design.

**Comment by daniel-bergmann** [comment]
Hi @SrNightmare09 , we have decided to keep the current logo for now, thanks for your contribution! Feel free to try another issue!
